Enforce clang-fromat version 16.0.xyz

diff --git a/scripts/t8indent b/scripts/t8indent
--- a/scripts/t8indent
+++ b/scripts/t8indent
@@ -31,6 +31,30 @@ FORMAT_OPTIONS="-i --style=file"
 
 FORMAT=`which clang-format 2> /dev/null`
 
+if [ -z "$FORMAT" ]
+then
+  # Exit if the spell checking script was not found
+  echo "ERROR: clang-format not found."
+  echo "Please install clang-format version 16.0.xyz"
+  echo "See https://github.com/ssciwr/clang-format-wheel"
+  exit 1
+fi
+
+CLANG_VERSION_STRING=`$FORMAT --version`
+
+VERSION=`echo $CLANG_VERSION_STRING | cut -d " " -f 3`
+MAJOR=`echo $VERSION | cut -d. -f1`
+MINOR=`echo $VERSION | cut -d. -f2`
+
+if [[ "$MAJOR" != "16" ]]; then
+  echo "Please install clang-format version 16.0.xyz"
+  exit 1
+fi
+if [[ $MINOR != "0" ]]; then
+  echo "Please install clang-format version 16.0.xyz"
+  exit 1
+fi
+
 for arg in "$@" ; do
   if [ "x$arg" == "x-o" ]; then
     WANTSOUT=1
